print("Welcome to the Haiku generator!")
print("Provide a first line for your haiku:")
first = str(raw_input())
print("Provide a second line for your haiku:")
second = str(raw_input())
print("Provide a third line for your haiku:")
third = str(raw_input())
print("What file would you like to write your haiku to?")
myFile = str(raw_input())
print("Done! To view your haiku, type 'cat' and the name of your file at the command line.")
my_File = open((myFile), "a")
my_File.write(first + '\n' + second + '\n' + third + '\n')
my_File.close()
